local utils = require "utils"
utils.map("n", "<Leader>bp", ":BufferPrevious<CR>")
utils.map("n", "<Leader>bn", ":BufferNext<CR>")
utils.map("n", "<Leader>mp", ":BufferMovePrevious<CR>")
utils.map("n", "<Leader>mn", ":BufferMoveNext<CR>")
utils.map("n", "<Leader>b1", ":BufferGoto 1<CR>")
utils.map("n", "<Leader>b2", ":BufferGoto 2<CR>")
utils.map("n", "<Leader>b3", ":BufferGoto 3<CR>")
utils.map("n", "<Leader>b4", ":BufferGoto 4<CR>")
utils.map("n", "<Leader>b5", ":BufferGoto 5<CR>")
utils.map("n", "<Leader>b6", ":BufferGoto 6<CR>")
utils.map("n", "<Leader>b7", ":BufferGoto 7<CR>")
utils.map("n", "<Leader>b8", ":BufferGoto 8<CR>")
utils.map("n", "<Leader>b9", ":BufferGoto 9<CR>")
utils.map("n", "<Leader>b0", ":BufferLast<CR>")
utils.map("n", "<Leader>bc", ":BufferClose<CR>")
utils.map("n", "<Leader>bs", ":BufferPick<CR>")
utils.map("n", "<Leader>bb", ":BufferOrderByBufferNumber<CR>")
utils.map("n", "<Leader>bd", ":BufferOrderByDirectory<CR>")
utils.map("n", "<Leader>bl", ":BufferOrderByLanguage<CR>")
