local utils = require "utils"
utils.map("n","<Leader>fn","<Cmd>FloatermNew<CR>")
utils.map("n","<Leader>fg","<Cmd>FloatermNew --name=lazygit lazygit<CR>")
utils.map("n","<Leader>fz","<Cmd>FloatermNew --name=fzf fzf<CR>")
utils.map("n","<Leader>fu","<Cmd>FloatermNew --name=ncdu ncdu<CR>")
utils.map("n","<Leader>ft","<Cmd>FloatermNew --name=gotop gotop<CR>")
utils.map("n","<Leader>fh","<Cmd>FloatermNew --name=htop htop<CR>")
utils.map("n","<Leader>fy","<Cmd>FloatermNew --name=yarn yarn start<CR>")
utils.map("n","<Leader>fr","<Cmd>FloatermNew --name=rescript yarn re:start<CR>")
utils.map("t","<Leader>fn","<C-\\><C-n><Cmd>FloatermNew<CR>")
utils.map("n","<Leader>ft","<Cmd>FloatermToggle<CR>")
utils.map("t","<Leader>ft","<C-\\><C-n><Cmd>FloatermToggle<CR>")
utils.map("n","<Leader>fk","<Cmd>FloatermKill<CR>")
utils.map("t","<Leader>fk","<C-\\><C-n><Cmd>FloatermKill<CR>")
utils.map("n","<Leader>fx","<Cmd>FloatermNext<CR>")
utils.map("t","<Leader>fx","<C-\\><C-n><Cmd>FloatermNext<CR>")
utils.map("n","<Leader>fp","<Cmd>FloatermPrev<CR>")
utils.map("t","<Leader>fp","<C-\\><C-n><Cmd>FloatermPrev<CR>")

vim.api.nvim_set_var("floaterm_height",0.96)
vim.api.nvim_set_var("floaterm_width",0.96)
